Repository StudentsAgainstCovid19/corona-aid-api, pull requests merged in 2020-06, with the labels that each got.

#4 Add test to InfectedController
  .github/workflows/ci-with-docker.yml
  .github/workflows/ci.yml
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/ContactRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DiseaseRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/HistoryRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InitialDiseaseRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/ResidentialGroupRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/SymptomRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/ConfigControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement

#8 Test endpoint
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement

#11 Feature/test endpoint
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
Labels: enhancement

#12 Feature/test endpoint
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ContactItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Test.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InitialDiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
Labels: enhancement

#13 Test/test endpoint
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#14 Renew production build
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ContactItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Test.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InitialDiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: release

#16 Fixes #15
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: bug

#18 Add ApiOperation annotations to all RequestMappings
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
Labels: documentation

#21 Remove ModelMapper holdover
  src/main/kotlin/com/chillibits/coronaaid/model/dto/ContactItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InitialDiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/ResidentialGroupDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/SymptomDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/TestDto.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/ConfigControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#24 Add mapping to get single affected / locking mechanism
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/advice/InfectedLockedAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/advice/InfectedNotFoundAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/exception/InfectedLockedException.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/exception/InfectedNotFoundException.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#26 Unlocking mechanism
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobs.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#27 Unlock infected on HistoryItem push
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
Labels: enhancement

#28 Unlock cron jobs
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
Labels: enhancement

#29 Extend tests and improve code style
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ConfigKeys.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/SymptomControllerTests.kt
Labels: enhancement, improvement

#31 Fix redundant locking flag
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: improvement

#32 Continuous release
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ConfigKeys.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/SymptomControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: release

#37 Add CORS policy definition
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
Labels: enhancement

#40 Fix history item push
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemInsertDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
Labels: bug, improvement

#41 Continuous release
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemInsertDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
Labels: release

#42 Support for compressed infected data
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedCompressedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#45 Lock / unlock manually with seperate put mappings
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement

#48 Some Swagger fixes / project cleanup
  .github/scripts/decrypt_secret.sh
  build.sh
  secrets.tar
  secrets.tar.gpg
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
Labels: improvement

#50 Add workflow for dev builds
  .github/workflows/ci-with-docker-develop.yml
Labels: improvement

#52 Add Swagger UI Configuration
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
Labels: documentation

#51 Fix infected performance
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ContactItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Test.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/TestDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/main/resources/application.yml
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement, improvement

#53 Add missing hashCode and equals
  src/main/kotlin/com/chillibits/coronaaid/model/db/ConfigItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ResidentialGroup.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Symptom.kt
Labels: improvement

#55 Allow "PUT" method for CORS
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
Labels: improvement

#56 Fix a bug when you push a history item the infected is not unlocked
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
Labels: bug, improvement

#54 Convert List to Set
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ResidentialGroup.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Symptom.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemInsertDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/HistoryRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/ConfigControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/SymptomControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: improvement

#57 Code optimization
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ConfigItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ContactItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ResidentialGroup.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Symptom.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Test.kt
Labels: improvement

#58 Add TestInsertDTO -> you dont have to send the testId with your post …
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/TestInsertDto.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: enhancement

#59 Add realtime endpoint test
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/WebSocketConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SocketTextHandler.kt
Labels: enhancement

#60 Add additional port
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
Labels: improvement

#62 Fix a issue that the endpoint is not reachable
  src/main/kotlin/com/chillibits/coronaaid/config/WebSocketConfig.kt
Labels: improvement

#63 Add new cors urls
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
Labels: improvement

#65 Add additional fields to InfectedCompressedDto
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedCompressedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement, improvement

#68 Fix tag names
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ResidentialGroup.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/ResidentialGroupDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/ResidentialGroupRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: improvement

#69 Add done flag to Infected DAO
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement

#70 Add getter so the flag is always up to date with the history collection
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
Labels: bug, improvement

#72 Cleanup data model
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InitialDiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InitialDiseaseRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
Labels: enhancement, improvement

#75 Add locked flag to InfectedCompressedDto
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedCompressedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: enhancement

#71 Continuous release
  README.md
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/WebSocketConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/InitialDisease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ResidentialGroup.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedCompressedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InitialDiseaseDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/ResidentialGroupDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InitialDiseaseRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/ResidentialGroupRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SocketTextHandler.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: release

#76 Throw exception, if test result is invalid on push
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/advice/InvalidTestResultAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/exception/InvalidTestResultException.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: improvement

#77 Add SSE Endpoint
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
  src/main/kotlin/com/chillibits/coronaaid/config/WebSocketConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/RealtimeController.kt
  src/main/kotlin/com/chillibits/coronaaid/events/InfectedChangeEvent.kt
  src/main/kotlin/com/chillibits/coronaaid/events/SseDataPreparedEvent.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedRealtimeDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/HistoryRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
Labels: enhancement, improvement

#79 Add header to prevent poxy caching
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/RealtimeController.kt
Labels: bug, improvement

#80 Fix realtime interval
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ConfigKeys.kt
Labels: improvement

#81 Fix synchronisation
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
Labels: improvement

#82 Add value restrictions for all models
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/model/db/ConfigItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/ContactItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Disease.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Symptom.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Test.kt
Labels: enhancement, improvement

#83 Add auto evaluation cron job
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/events/InfectedChangeEvent.kt
  src/main/kotlin/com/chillibits/coronaaid/events/SseDataPreparedEvent.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/TestRepository.kt
Labels: enhancement

#84 Fix problems with realtime endpoint
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/service/InfectedService.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: documentation, enhancement, improvement

#85 Fix time zone issue with call list
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DateTimeExtension.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/ModelToDtoMappers.kt
Labels: improvement

#87 Project cleanup
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/HistoryController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SocketTextHandler.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
Labels: documentation, improvement

#88 Feature timestamp conversion
  src/main/kotlin/com/chillibits/coronaaid/model/dto/HistoryItemDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedCompressedDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/TestDto.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/DateTimeConverters.kt
Labels: enhancement

#89 Add sorting annotations for tests and history items
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
Labels: improvement

#90 Add exception for pending tests on pushing tests
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/TestController.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/advice/OnlyOnePendingTestAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/exception/exception/OnlyOnePendingTestException.kt
Labels: improvement

#92 Add update flag
  src/main/kotlin/com/chillibits/coronaaid/model/dto/InfectedDto.kt
Labels: enhancement, improvement

#95 Discard unnecessary events
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
Labels: improvement
