Repository StudentsAgainstCovid19/corona-aid-api, pull requests merged in 2020-07, with the labels that each got.

#93 Add additional test for quality ensurance
  README.md
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: improvement

#97 Feature district endpoint
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/District.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictAnalyticsDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
  src/main/resources/application.yml
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/DistrictControllerTests.kt
Labels: enhancement, improvement

#98 Improve api performance
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
Labels: improvement

#96 Continuous release
  README.md
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/RealtimeTask.kt
  src/main/kotlin/com/chillibits/coronaaid/config/RoutingConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/District.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/Infected.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictAnalyticsDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/DtoToModelMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
  src/main/resources/application.yml
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/DistrictControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/HistoryControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/TestControllerTests.kt
Labels: release

#101 Update er diagram
  media/er_diagram.dia
  media/er_diagram.dia~
  media/er_diagram.png
Labels: improvement

#109 Update Readme to reflect ER diagram changes
  README.md
Labels: documentation

#110 Add routine to generate HistoryItems at midnight (Fix #107)
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/service/InfectedService.kt
Labels: enhancement

#102 Improve code style
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/DistrictControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: improvement

#112 Fix district sql
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
Labels: improvement

#113 Implement XML serializer
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/JacksonConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/JtsGeometryXMLSerializer.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/District.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictAnalyticsDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictDto.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/DistrictControllerTests.kt
Labels: enhancement, improvement

#115 Add Jackson double serializer
  src/main/kotlin/com/chillibits/coronaaid/config/JacksonConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/JacksonDoubleSerializer.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/JacksonJtsGeometryXMLSerializer.kt
Labels: improvement

#111 Continuous release
  README.md
  media/er_diagram.dia
  media/er_diagram.dia~
  media/er_diagram.png
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/CoronaAidApplication.kt
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/JacksonConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/JacksonDoubleSerializer.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/JacksonJtsGeometryXMLSerializer.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/District.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictAnalyticsDto.kt
  src/main/kotlin/com/chillibits/coronaaid/model/dto/DistrictDto.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/DistrictRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/repository/InfectedRepository.kt
  src/main/kotlin/com/chillibits/coronaaid/service/InfectedService.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/DistrictControllerTests.kt
  src/test/kotlin/com/chillibits/coronaaid/controller/v1/InfectedControllerTests.kt
Labels: release

#117 Add XML DTD injector
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/XmlDtdBodyAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/XmlDtdUrl.kt
Labels: enhancement, improvement

#118 Bugfixes
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
Labels: improvement

#119 Adjusted xml dtd urls
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
Labels: enhancement

#120 Continuous release
  README.md
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/XmlDtdBodyAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/XmlDtdUrl.kt
Labels: release

#121 Fix wrong values
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
Labels: bug

#124 Add infinite timeout
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/RealtimeController.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
Labels: improvement

#125 Remove data generation cron
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
Labels: improvement

#126 Continuous release
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/RealtimeController.kt
  src/main/kotlin/com/chillibits/coronaaid/model/db/HistoryItem.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/SseEmitterStorage.kt
Labels: release

#128 DTD Fixes
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/XmlDtdBodyAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/XmlDtdUrl.kt
Labels: bug, improvement

#129 Update README.md
  README.md
Labels: documentation

#130 Change collection type
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
Labels: improvement

#131 Fix calculation of sum
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/ModelToDtoMappers.kt
Labels: bug

#132 Add experimental prepare data function
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/PrepareDataTask.kt
Labels: enhancement, improvement

#127 Release to v1.0.0
  README.md
  pom.xml
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/config/PrepareDataTask.kt
  src/main/kotlin/com/chillibits/coronaaid/config/SwaggerConfig.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/ConfigController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/DistrictController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/InfectedController.kt
  src/main/kotlin/com/chillibits/coronaaid/controller/v1/SymptomController.kt
  src/main/kotlin/com/chillibits/coronaaid/jackson/XmlDtdBodyAdvice.kt
  src/main/kotlin/com/chillibits/coronaaid/model/mapper/ModelToDtoMappers.kt
  src/main/kotlin/com/chillibits/coronaaid/shared/XmlDtdUrl.kt
Labels: release

#133 Remove method call
  src/main/kotlin/com/chillibits/coronaaid/config/CronJobsConfig.kt
Labels: bug
